"use client";

import Apply from "@/app/components/Apply";
import PageLayout from "@/app/components/PageLayout";
import { Shield, Activity, Target, CheckCircle2, MapPin, Briefcase, Users, Zap, Radio, Wifi, Satellite, Cpu } from "lucide-react";
import { motion } from "framer-motion";

export default function TelemetryEngineerPage() {
  return (
    <PageLayout
      title={
        <>
          Role: <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">RF / Telemetry Engineer</span>
        </>
      }
      subtitle="Ensure unbroken communication between the launch vehicle and ground control at supersonic speeds."
    >
      <div className="grid lg:grid-cols-12 gap-10 mt-12">
        
        {/* --- LEFT COLUMN: MISSION DETAILS (Span 8) --- */}
        <div className="lg:col-span-8 space-y-16">
          
          {/* 1. MISSION OVERVIEW CARD */}
          <motion.section 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="relative bg-white/[0.02] border border-white/10 p-8 md:p-10 rounded-3xl backdrop-blur-md overflow-hidden group"
          >
            <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/hexellence.png')] opacity-10 group-hover:opacity-20 transition-opacity duration-500" />
            <div className="absolute -bottom-20 -right-20 w-80 h-80 bg-cyan-500/20 rounded-full blur-[100px] pointer-events-none group-hover:bg-cyan-500/30 transition-all duration-1000" />
            
            <div className="relative z-10">
                <div className="flex items-center gap-3 mb-6">
                    <div className="p-2 bg-cyan-500/10 rounded-lg text-cyan-400 border border-cyan-500/20">
                        <Target size={24} />
                    </div>
                    <h3 className="text-xl font-bold text-white tracking-wide">
                        Mission Overview
                    </h3>
                </div>
                
                <p className="text-white/70 leading-relaxed text-lg font-light">
                    At <strong className="text-white font-medium">Algoforge Aerospace</strong>, if we don't capture the data, the flight didn't happen. 
                    <br/><br/>
                    You will own the invisible tether between our rockets and the ground. From the <span className="text-cyan-400">Node 2 Onboard Flight Computer</span> to the <span className="text-cyan-400">Node 3 Ground Station</span>, you are responsible for maintaining high-fidelity RF links (LoRa, S-Band) through the extreme noise, vibration, and plasma of a rocket launch.
                </p>
            </div>
          </motion.section>

          {/* 2. RESPONSIBILITIES */}
          <section className="space-y-8">
              <div className="flex items-center gap-4 border-b border-white/10 pb-4">
                 <div className="h-1 w-12 bg-cyan-500 rounded-full" />
                 <h3 className="text-2xl font-bold text-white tracking-tight">Operational Objectives</h3>
              </div>
              
              <div className="grid gap-4">
                 <ListItem text="Architect and optimize the RF communication link budgets for launch vehicle telemetry and command uplinks." delay={0.1} />
                 <ListItem text="Design, tune, and integrate custom antennas for ESP32-based flight computers (433MHz / 915MHz LoRa) and future S-Band systems." delay={0.2} />
                 <ListItem text="Develop embedded C++ firmware to serialize, compress, and transmit high-speed sensor data (IMU, Barometer, Load Cells) with zero latency." delay={0.3} />
                 <ListItem text="Mitigate EMI/RFI (Electromagnetic Interference) generated by the VORTEX-1 engine, servos, and high-power ignition relays." delay={0.4} />
                 <ListItem text="Bridge the hardware-to-software gap by piping raw Node 3 receiver data directly into our Next.js Mission Director Dashboard via USB/Serial APIs." delay={0.5} />
              </div>
          </section>

          {/* 3. QUALIFICATIONS */}
          <section className="space-y-8">
              <div className="flex items-center gap-4 border-b border-white/10 pb-4">
                 <div className="h-1 w-12 bg-blue-500 rounded-full" />
                 <h3 className="text-2xl font-bold text-white tracking-tight">Mission Prerequisites</h3>
              </div>

              <div className="grid gap-4">
                 <ListItem text="B.S. or M.S. in Electrical Engineering, Computer Engineering, or Telecommunications." delay={0.1} />
                 <ListItem text="Proven experience with RF hardware design, antenna tuning (VNA usage), and link budget analysis." delay={0.2} />
                 <ListItem text="Strong C/C++ embedded programming skills, specifically with ESP32/STM32 microcontrollers and SPI/I2C buses." delay={0.3} />
                 <ListItem text="Deep understanding of modulation schemes (LoRa, FSK) and error correction protocols." delay={0.4} />
                 <ListItem text="Experience with SDRs (Software Defined Radios) and signal processing is highly preferred." delay={0.5} />
              </div>
          </section>

          {/* 4. PERKS GRID */}
          <section>
              <h3 className="text-sm font-bold text-white/40 uppercase tracking-[0.2em] mb-8 text-center">
                 — Deployment Benefits —
              </h3>
              <div className="grid md:grid-cols-2 gap-4">
                 <PerkItem icon={Radio} title="The Lifeline" text="Your architecture is the only way the vehicle talks to the ground." />
                 <PerkItem icon={Wifi} title="Full Spectrum" text="Work across the entire stack, from bare metal antennas to JSON APIs." />
                 <PerkItem icon={Cpu} title="Embedded Mastery" text="Push ESP32 hardware to its absolute limits under extreme G-forces." />
                 <PerkItem icon={Satellite} title="Data Integrity" text="Ensure the VORTEX-1 research data survives the flight." />
              </div>
          </section>

        </div>

        {/* --- RIGHT COLUMN: METADATA & APPLY (Span 4) --- */}
        <div className="lg:col-span-4 space-y-8">
          
          <motion.div 
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="bg-black/40 border border-white/10 p-6 rounded-2xl relative overflow-hidden backdrop-blur-xl"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-cyan-500/20 blur-[60px] pointer-events-none" />
            
            <h4 className="text-xs font-bold text-white/40 uppercase tracking-widest mb-6 flex items-center gap-2">
                <Briefcase size={14} /> Position Intelligence
            </h4>
            
            <div className="space-y-6">
              <MetaRow icon={Shield} label="Department" value="Avionics & Software" />
              <MetaRow icon={MapPin} label="Location" value="Bengaluru, KA" />
              <MetaRow icon={Users} label="Openings" value="1 Position Available" />
              <MetaRow icon={Activity} label="Domain" value="RF & Embedded C++" />
              <MetaRow icon={Radio} label="Environment" value="High-EMI / Long Range" />
            </div>

            <div className="mt-8 pt-6 border-t border-white/10">
                <div className="flex items-center gap-3">
                    <div className="w-2 h-2 rounded-full bg-cyan-500 animate-pulse" />
                    <span className="text-xs font-mono text-cyan-400 uppercase tracking-widest">
                        Priority: High
                    </span>
                </div>
            </div>
          </motion.div>

          <div className="sticky top-24">
             <Apply role="RF / Telemetry Engineer" />
          </div>
          
        </div>
      </div>
    </PageLayout>
  );
}

function ListItem({ text, delay }: { text: string, delay: number }) {
  return (
    <motion.div 
        initial={{ opacity: 0, x: -10 }}
        whileInView={{ opacity: 1, x: 0 }}
        viewport={{ once: true }}
        transition={{ delay, duration: 0.5 }}
        className="flex items-start gap-4 group p-3 rounded-xl hover:bg-white/5 transition-colors"
    >
      <div className="mt-1 min-w-[20px]">
         <CheckCircle2 className="text-cyan-500/50 group-hover:text-cyan-400 transition-colors" size={20} />
      </div>
      <span className="text-white/80 leading-relaxed font-light text-sm md:text-base group-hover:text-white transition-colors">{text}</span>
    </motion.div>
  );
}

function PerkItem({ icon: Icon, title, text }: any) {
    return (
        <div className="flex items-start gap-4 bg-white/[0.03] p-4 rounded-xl border border-white/5 hover:border-cyan-500/30 hover:bg-white/[0.06] transition-all group">
            <div className="p-2 bg-black rounded-lg text-white/60 group-hover:text-cyan-400 group-hover:scale-110 transition-all border border-white/10"><Icon size={18} /></div>
            <div>
                <h4 className="text-sm font-bold text-white mb-1">{title}</h4>
                <p className="text-xs text-white/50 leading-relaxed">{text}</p>
            </div>
        </div>
    )
}

function MetaRow({ icon: Icon, label, value }: any) {
  return (
    <div className="flex items-center gap-4 group">
      <div className="p-2.5 bg-white/5 rounded-lg text-white/40 border border-white/5 group-hover:border-cyan-500/30 group-hover:text-cyan-400 group-hover:bg-cyan-500/10 transition duration-300"><Icon size={18} /></div>
      <div>
        <p className="text-[9px] text-white/30 uppercase font-bold tracking-wider mb-0.5">{label}</p>
        <p className="text-white font-mono text-sm tracking-tight">{value}</p>
      </div>
    </div>
  );
}
